[project]
name = "advanced-omi-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easy-audio-interfaces>=0.5.1",
    "fastapi>=0.115.12",
    "mem0ai>=0.1.111",
    "motor>=3.7.1",
    "ollama>=0.4.8",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
    "wyoming>=1.6.1",
    "aiohttp>=3.8.0",
    "langfuse==3.3.0",
    "spacy>=3.8.2",
    "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl",
]

[dependency-groups]
deepgram = [
    "deepgram-sdk>=4.0.0",
]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
]
tests = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]


[tool.isort]
profile = "black"

[tool.uv.sources]
useful-moonshine-onnx = { git = "https://github.com/usefulsensors/moonshine.git", subdirectory = "moonshine-onnx" }
torchaudio  = { index = "pytorch-cu128",   marker = "sys_platform != 'darwin'" }
torchvision  = { index = "pytorch-cu128",   marker = "sys_platform != 'darwin'" }
torch = [
  { index  = "pytorch-cu128", marker = "sys_platform != 'darwin'" },
]

[[tool.uv.index]]
name = "pypi"
url  = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-cu128"
url  = "https://download.pytorch.org/whl/cu128"
